[package]
name = "pinboard-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.1"
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "json", "sqlite"] }
serde = "1.0.152"
anyhow = "1.0.68"
url = "2.3.1"
